name: Sanity Test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make lint
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install

